// Generated by Haxe 3.4.0
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	(function(input) {
		var el = input.split(" ");
		if(el.length == 4) {
			if(el[0] == "say") {
				if(el[2] == "to") {
					switch(el[3]) {
					case "Emma":case "Olivia":case "Sophia":
						break;
					default:
					}
				}
			}
		}
	})("say hi to Mark");
};
Main.main();
})();
